### ISSUE TITLE
Show app icon on the notification

### ISSUE THREAD

**Issue by sidevesh** [sannidhyaroy/Soduto#17]
Currently the app shows Soduto icon for every notification, it would look a lot more seamless if it rather used the app's own icon like kdeconnect does on linux desktop.

**Comment by sannidhyaroy** [comment]
That won’t be possible because of how things work on macOS. Soduto just sends a request to macOS to add a notification with a title, body and optional attachments. It's macOS that actually pushes the notification and it'll always include the app icon of the app that requested to push the notification.
That being said, currently Soduto sends the app icon for some apps like YouTube, Twitter, Reddit, etc. as an attachment along with the notification. So basically for apps like YouTube, you'll see the Soduto icon as well as the YouTube icon in the notification. This is how KDE Connect also works on macOS as it's fundamentally not possible to just not have the app icon of the app which sent the notification.

KDE Connect/Zorin Connect on the other device actually sends a payload containing a png file the app icon that pushed the notification and I've attempted to extract that png file from the payload multiple times since the past 8 months. If I can make use of that png file from the payload, Soduto will be able to push the app icon as an attachment along with the notification request for every app, not just a few selected apps like it currently does.

So, for the time being, I have to manually inject pre-made app icons for a few selected apps that we commonly use. If you have any app that you want me to add an app icon for, you can open an issue on this repository, provided that the app is not uncommon or niche as shipping every possible app icon along with Soduto will increase the app size.

**Comment by sidevesh** [comment]
got it, I knew that KDE COnnect sends the app icon, didn't know its a headache to extract it,
I am planning to take a look once I have Mac OS development setup on my MacBook,
just in case, I had found this https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/main/src/service/plugins/notification.js#L542 in gsconnect related to getting the notification app icon,
does this seem relevant to the issue ?

**Comment by sannidhyaroy** [comment]
Yes it is relevant to this issue. However I tried to reverse engineer to extract the app icon from the payload by digging up at KDE Connect's code but couldn’t cuz things on the Soduto's side seemed a bit different like Soduto was receiving the payload as an `InputStream`. I've talked about the issue in detail [here](https://github.com/soduto/Soduto/issues/29) a couple of months back...

**Comment by sidevesh** [comment]
@sannidhyaroy did you try the recommendation https://github.com/soduto/Soduto/issues/29#issuecomment-1568921122 ?
That looks to me like what gsconnect is also doing.

**Comment by sannidhyaroy** [comment]
> @sannidhyaroy did you try the recommendation https://github.com/soduto/Soduto/issues/29#issuecomment-1568921122 ?

Nope, I haven't been able to extract the png from the payload till now. And the other KDE Connect clients have a different codebase. I tried following through their code and tried to implement for Soduto but couldn't.

**Comment by sidevesh** [comment]
does it not work with the downloadTask function either ?

**Comment by sidevesh** [comment]
also I know there are priivate apis that allow you to set the app icon also in the notification to whatever you want,
if we manage to get the notification's icon successfully, the notification integration can be made really seamless but just showing that icon in the notification rather than Soduto's.
I will find the relevant code from the libraries I have seen implementing this and share it here.

**Comment by sannidhyaroy** [comment]
> does it not work with the downloadTask function either ?

I couldn't figure out how to use `dataPacket.downloadTask`. I went through the code in the `ShareService` to see how it uses `downloadTask` and I nearly fainted. 😂
