### ISSUE TITLE
Auto select device

### ISSUE THREAD

**Issue by electr1fy0** [sannidhyaroy/Soduto#2]
Is it possible to have the device automatically selected when using Drag and Drop to Menu Bar icon, if there is only one device paired?

**Comment by sannidhyaroy** [comment]
@electr1fy0 The reason I don't think it's a good idea is because there are times when some devices automatically disconnect from `Soduto`, possibly because Android stopped the background process of `KDE/Zorin Connect` or some other reasons. In such cases, the user may expect the device name to show up in the panel when they drag a file to the menu bar icon but instead it automatically sends to another connected device.

However it isn't a completely bad idea as it will save time in most of the cases and will be seamless. So, I'll try to give a toggle in `Soduto Preferences` to enable such a feature, along with a warning to inform users of the possible drawbacks.

I'm quite busy recently due to my upcoming exams, if I implement such a feature in the future, I'll update this `issue` and notify you.

**Comment by electr1fy0** [comment]
Wow, thanks for implementing such a minor QOL request. I was totally expecting this to be ignored, XD.

I tested it by building it and it works perfectly.
