### ISSUE TITLE
Dismiss button doesn't work

### ISSUE THREAD

**Issue by marekmasek** [sannidhyaroy/Soduto#32]
When I click on dismiss button for some notification on Mac I still have the notification on my phone, just the body is gone, but the header of the notification is still there. Does dismiss button work for you?

**Comment by sannidhyaroy** [comment]
It does work for me. Ofc, only if Soduto is still paired to the phone, it basically sends a dismiss request to KDE Connect or Zorin Connect on your phone. Also, KDE Connect or Zorin Connect needs some permissions on android to dismiss the notification. But since, your saying it doesn't work for "some" notifications, it'll help to debug the issue if you can provide some more info on this.

**Comment by marekmasek** [comment]
It's not working for me for all notifications, but probably the issue is on the side of KDE Connect. I have Pixel 8 Pro running latest Android 14 and latest version of KDE Connect (v 1.29.0). I attached the screenshot of example what happens when I use dismiss button on one of the notifications, I used it on the second notification from **Email.cz** app. You can see that the notification is still there, just the title and text body of the notification disappeared.


**Before dismiss:**
![Before dismiss](https://github.com/sannidhyaroy/Soduto/assets/48589322/80e9bd3a-3d3b-4e74-bd76-581307055950)
**After dismiss:**
![After dismiss](https://github.com/sannidhyaroy/Soduto/assets/48589322/3d20d297-4af4-4d9b-8a9b-3b31d47c0f37)

**Comment by sannidhyaroy** [comment]
I see, since the notification content disappears, it's more likely that Soduto does send the dismiss request to KDE Connect but the app on your phone for some reason can't complete the action. Soduto's job is to only send the cancel request along with the notification id of the notification to be canceled. KDE Connect on your phone is responsible to actually dismiss the notification that's associated with the received notification id.

**Comment by marekmasek** [comment]
I see, thanks! I'm going to report to KDE. Closing the issue...
